### ISSUE TITLE
Trouble getting streams to play via Plex Tuner

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/mlbserver#2]
Hey there- great product, I've been using it to cast games to Plex. I loaded mlbserver into Plex as a tuner, and I could get the proper xml guide, but every stream linked back to the samples you have built in.

I tested https://github.com/taylorbourne/xteve_lazystream alongside it, and found that the links provided to Plex are different.

**Comment by tonywagner** [comment]
Sorry I didn't notice this until just now!

> but every stream linked back to the samples you have built in

This is by design if "Scan Mode" is set to "on" via the server homepage. I created that option so my DVR server (TVHeadend) could detect streams as valid even if games weren't currently live, and to prevent hammering game requests when initially scanning the M3U.

**Comment by ahughes03** [comment]
That totally worked. You'd even included a description of the "Scan Mode" toggle settings, and it completely wooshed over my head. Thanks for the help!
